In [2]:
import numpy as np

In [3]:
x = np.arange(12).reshape(3,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [6]:
# x와 같은 shape를 가진 배열을 1로 채워라
np.ones_like(x)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [7]:
# x와 같은 shape를 가진 배열을 0으로 채워라
np.zeros_like(x)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [10]:
# identity 단위 행렬, 매개변수 n으로 n×n 단위행렬을 생성
# 이런 형식으로 나옴
np.identity(n=3, dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [11]:
np.identity(n=4, dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [12]:
# eye 함수 : 시작점과 행렬 크기를 지정, 단위행렬 생성 N은 행의 개수, M은 열의 개수를 지정, k는 열의 값을 기준으로 시작 인덱스
np.eye(N=3, M=5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [13]:
np.eye(N=3, M=5, k=2)

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [14]:
#  diag 함수 : 행렬의 대각성분 값을 추출
matrix = np.arange(9).reshape(3,3)
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [15]:
np.diag(matrix)

array([0, 4, 8])

In [16]:
np.diag(matrix, k=1)

array([1, 5])

In [22]:
# uniform 함수 : 균등분포 함수, np.random.uniform(시작값, 끝값, 데이터개수)’
np.random.uniform(0, 5, 10)

array([0.25494904, 2.1741694 , 4.41494113, 3.09833655, 0.7936191 ,
       4.47726956, 1.86522976, 4.94898641, 3.18479757, 2.46995618])

In [28]:
#  normal 함수 : 정규분포 함수, np.random.normal(평균값, 분산, 데이터개수)’
np.random.normal(0, 2, 10)

array([ 2.22555746, -0.00737011, -1.31111906, -1.14815278,  4.55147825,
       -0.29200901, -2.82798422, -0.40947747,  0.9267643 , -0.86608383])

In [29]:
import numpy as np
test_array = np.arange(1, 11)
test_array.sum()

55

In [30]:
test_array = np.arange(1,13).reshape(3,4)
test_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [35]:
# axis 0이면 x축 방향(가로줄끼리 더한다)
test_array.sum(axis=0)

array([15, 18, 21, 24])

In [36]:
# axis 0이면 y축(세로줄끼리 더한다.)
test_array.sum(axis=1)

array([10, 26, 42])

In [37]:
# 3차원배열
test_array = np.arange(1, 13).reshape(3, 4)
third_order_tensor = np.array([test_array,test_array, test_array])
third_order_tensor

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [38]:
# 3차원 배열의 axis 0은 z축(다른집 같은자리끼리 더한다)
third_order_tensor.sum(axis=0)

array([[ 3,  6,  9, 12],
       [15, 18, 21, 24],
       [27, 30, 33, 36]])

In [39]:
# 3차원 배열의 axis 1은 y축(세로줄끼리 더한다.)
third_order_tensor.sum(axis=1)

array([[15, 18, 21, 24],
       [15, 18, 21, 24],
       [15, 18, 21, 24]])

In [41]:
# 3차원 배열의 axis 2는 x축(가로줄끼리 더한다)
third_order_tensor.sum(axis=2)

array([[10, 26, 42],
       [10, 26, 42],
       [10, 26, 42]])

In [42]:
test_array = np.arange(1, 13).reshape(3, 4)
test_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [43]:
test_array.mean(axis=1)

array([ 2.5,  6.5, 10.5])

In [44]:
test_array.std() # 전체 값에 대한 표준편차 연산

3.452052529534663

In [45]:
test_array.std(axis=0)

array([3.26598632, 3.26598632, 3.26598632, 3.26598632])

In [47]:
np.sqrt(test_array) # 각 요소에 제곱근 연산 수행(square root)

array([[1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712],
       [3.        , 3.16227766, 3.31662479, 3.46410162]])

In [50]:
# vstack 함수 : 배열을 수직으로 붙여 하나의 행렬을 생성
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])
np.vstack((v1, v2))

array([[1, 2, 3],
       [4, 5, 6]])

In [54]:
# hstack 함수 : 배열을 수평으로 붙여 하나의 행렬을 생성
np.hstack((v1,v2))

array([1, 2, 3, 4, 5, 6])

In [57]:
v1 = v1.reshape(-1, 1)
v2 = v2.reshape(-1, 1)
v1

array([[1],
       [2],
       [3]])

In [56]:
np.hstack((v1,v2))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [63]:
# concatenate 함수 : 축을 고려하여 두 개의 배열을 결합
v1 = np.array([[1, 2, 3]])
v2 = np.array([[4, 5, 6]])
np.concatenate((v1,v2), axis=0)
# axis = 0은 y축으로 붙임 union느낌

array([[1, 2, 3],
       [4, 5, 6]])

In [61]:
v1 = np.array([1, 2, 3, 4]).reshape(2,2)
v2 = np.array([[5,6]]).T
v2

array([[5],
       [6]])

In [64]:
# axis = 1은 x축으로 붙임 join느낌
np.concatenate((v1,v2), axis=1)

array([[1, 2, 3, 4, 5, 6]])

## 사칙연산 함수
### 같은 배열의 구조일 때 요소별 연산(element-wise operation)
 -요소별 연산 : 두 배열의 구조가 동일할 경우 같은 인덱스 요소들끼리 연산

In [65]:
x = np.arange(1, 7).reshape(2,3)
x

array([[1, 2, 3],
       [4, 5, 6]])

In [66]:
x + x

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [67]:
x - x

array([[0, 0, 0],
       [0, 0, 0]])

In [68]:
x / x

array([[1., 1., 1.],
       [1., 1., 1.]])

In [69]:
x ** x

array([[    1,     4,    27],
       [  256,  3125, 46656]])

### 배열 간의 곱셈에서는 요소별 연산과 벡터의 내적(dot product) 연산 가능
#### 벡터의 내적 : 두 배열 간의 곱셈
#### 두 개의 행렬에서 첫 번째 행렬의 열 크기와 두 번째 행렬의 행 크기가 동일해야 함
#### m×n 행렬과 n×l 행렬, 벡터의 내적 연산하면 m×l의 행렬 생성

In [70]:
# dot 함수 : 벡터의 내적 연산
x_1 = np.arange(1, 7).reshape(2,3)
x_2 = np.arange(1, 7).reshape(3,2)
x_1

array([[1, 2, 3],
       [4, 5, 6]])

In [71]:
x_2

array([[1, 2],
       [3, 4],
       [5, 6]])

In [72]:
x_1.dot(x_2)

array([[22, 28],
       [49, 64]])

In [73]:
# 브로드캐스팅 연산
x = np.arange(1, 10).reshape(3,3)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [74]:
x + 10

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [75]:
x -2

array([[-1,  0,  1],
       [ 2,  3,  4],
       [ 5,  6,  7]])

In [76]:
x // 3

array([[0, 0, 1],
       [1, 1, 2],
       [2, 2, 3]], dtype=int32)

In [77]:
x ** 2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [80]:
y1 = np.array([[0, 0, 0], [10 ,10, 10], [20, 20 ,20], [30, 30, 30]])
y2 = np.array([1, 2, 3])
y1 + y2

array([[ 1,  2,  3],
       [11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [87]:
y1 = np.array([[0, 0, 0], [10 ,10, 10], [20, 20 ,20], [30, 30, 30]])
y2 = np.array([[1, 2, 3, 4]]).T
y1 + y2

array([[ 1,  1,  1],
       [12, 12, 12],
       [23, 23, 23],
       [34, 34, 34]])

In [88]:
y2

array([[1],
       [2],
       [3],
       [4]])

In [81]:
g1 = np.array([[0, 10 , 20, 30]]).T
g2 = np.array([1, 2, 3])
g1+g2

array([[ 1,  2,  3],
       [11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [82]:
g1

array([[ 0],
       [10],
       [20],
       [30]])

In [90]:
# 비교 연산자
import numpy as np
x = np.array([4, 3, 2, 6, 8, 5]) 
x > 3

array([ True, False, False,  True,  True,  True])

In [91]:
# 두 개의 배열 간 배열의 구조(shape)가 동일한 경우
# 같은 위치에 있는 요소들끼리 비교 연산
# [1 ＞ 2, 3 ＞ 1, 0 ＞ 7] 과 같이 연산이 실시된 후 이를 반환
x = np.array([1, 3, 0])
y = np.array([2, 1, 7])
x > y

array([False,  True, False])

In [92]:
x = np.array([4, 6, 7, 3, 2])
(x > 3)

array([ True,  True,  True, False, False])

In [93]:
# all 함수 : 배열 내부의 모든 값이 참일 때는 True, 하나라도 참이 아닐 경우에는 False를 반환
# and 조건을 전체 요소에 적용
(x > 3).all()

False

In [94]:
# any 함수 : 배열 내부의 값 중 하나라도 참일 때는 True, 모두 거짓일 경우 False를 반환
# or 조건을 전체 요소에 적용
(x > 3).any()

True

In [95]:
# where 함수 : 배열이 불린형으로 이루어졌을 때 참인 값들의 인덱스를 반환
x = np.array([4, 6, 7, 3, 2])
np.where(x>5)

(array([1, 2], dtype=int64),)

In [98]:
# 참일 경우에 10을, 거짓일 경우에 20을 반환
x = np.array([4, 6, 7, 3, 2])
np.where(x>5 , 10, 20)

array([20, 10, 10, 20, 20])

In [99]:
# argsort : 배열 내 값들을 작은 순서대로 인덱스를 반환
x = np.array([4, 6, 7, 3, 2])
np.argsort(x)

array([4, 3, 0, 1, 2], dtype=int64)

In [100]:
# argmax : 배열 내 값들 중 가장 큰 값의 인덱스를 반환
np.argmax(x)

2

In [101]:
# argmin : 배열 내 값들 중 가장 작은 값의 인덱스를 반환
np.argmin(x)

4

In [112]:
# 불린 인덱스(boolean index) : 배열에 있는 값들을 반환할 특정 조건을 불린형의 배열에 넣어서 추출
# 인덱스에 들어가는 배열은 불린형이어야 함
# 불린형 배열과 추출 대상이 되는 배열의 구조가 같아야 함
x = np.array([4, 6, 7, 3, 2])
x > 3

array([ True,  True,  True, False, False])

In [113]:
cond = x > 3
x[cond]

array([4, 6, 7])

In [114]:
x.shape

(5,)

In [115]:
cond.shape

(5,)

In [116]:
x[cond].shape

(3,)

In [117]:
# 팬시 인덱스(fancy index) : 정수형 배열의 값을 사용하여 해당 정수의 인덱스에 위치한 값을 반환
# 인덱스 항목에 넣을 배열은 정수로만 구성되어야 함
# 정수 값의 범위는 대상이 되는 배열이 가지는 인덱스의 범위 내 대상이 되는 배열과 인덱스 배열의 구조(shape)가 같을 필요는 없음
x = np.array([4, 6, 7, 3, 2])
cond = np.array([1, 2, 0, 2, 2, 2,], int)
x[cond]

array([6, 7, 4, 7, 7, 7])

In [118]:
x.take(cond)

array([6, 7, 4, 7, 7, 7])

In [119]:
x = np.array([[1,4], [9,16]], int)
a = np.array([0, 1, 1, 1, 0, 0], int)
b = np.array([0, 0, 0, 1, 1, 1], int)
x[a,b]

array([ 1,  9,  9, 16,  4,  4])