In [1]:
import numpy as np
tl = [[1, 4, 5, 8], [1, 4, 5, 8]]
np.array(tl, float)  

array([[1., 4., 5., 8.],
       [1., 4., 5., 8.]])

In [2]:
import numpy as np
test_array = np.array([1, 4, 5, 8], float)
test_array

array([1., 4., 5., 8.])

In [3]:
type(test_array[3])

numpy.float64

In [4]:
test_array = np.array([1, 4, 5, "8"], float) 
print(test_array)
# print를 쓰면 array를 무시하나 데이터만 나온다.

[1. 4. 5. 8.]


In [5]:
print(type(test_array[3])) # 실수형(floating Type)으로 자동 형 변환 실시
# 이렇게 뽑으면 앞에 class 가 붙는다.

<class 'numpy.float64'>


In [12]:
# ndim은 차원을 알고 싶을 때
tensor_rank3 = [[[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]],
                [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]], 
                [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]],
                [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]] ]
np.array(tensor_rank3, int).ndim

3

In [13]:
# size는 전체 원소의 갯수
np.array(tensor_rank3, int).size

48

In [8]:
np.array([1, 4, 5, 8], float)
np.array( [ [1, 2, 3.5], [4, 5, 6.5]], dtype=int)
# 위 두 방법은 똑같은거다 편한거 쓰면 될 듯

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
# itemsize 요소(property)로 넘파이 배열에서 각 요소가 차지하는 바이트(byte) 확인
# np.float64로 dtype을 선언하면 64비트, 즉 8바이트 차지
np.array( [[1, 2, 3.5], [4, 5, 6.5]], float).itemsize

8

In [16]:
# np.float32로 dtype을 선언하면 32비트, 즉 4바이트 차지
np.array( [[1, 2, 3.5], [4, 5, 6.5]], dtype=np.float32).itemsize

4

In [33]:
# shape는 배열의 구조를 나타냄
x = np.array([[1, 2, 5, 8], [1, 2, 5, 8]])
x.shape

(2, 4)

In [34]:
# reshape : 원하는 형태로 구조를 조정함.
x.reshape(-1,)

array([1, 2, 5, 8, 1, 2, 5, 8])

In [35]:
# reshape : 원하는 형태로 구조를 조정함.
x.reshape(-1,).shape

(8,)

In [36]:
x

array([[1, 2, 5, 8],
       [1, 2, 5, 8]])

In [41]:
x = np.array(range(0, 11, 2))
x

array([ 0,  2,  4,  6,  8, 10])

In [62]:
# size가 맞아야 만들수 있다.
x.reshape(2, 2)
x.reshape(2, 7)


ValueError: cannot reshape array of size 8 into shape (2,2)

In [48]:
x = np.array(range(8)).reshape(4,2)
x

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [49]:
# -1는 상황에 맞게 만들어줌
x.reshape(2,-1)

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [64]:
# reshape(3차원수, 2차원수, 행수)
x.reshape(2,2,-1)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [60]:
# flatten() : 1차원으로 만들어 준다.
x.flatten().shape

(8,)

In [67]:
a = np.array([1, 2, 3, 4])
b = np.array([[2], [3], [4], [5]])
a*b

array([[ 2,  4,  6,  8],
       [ 3,  6,  9, 12],
       [ 4,  8, 12, 16],
       [ 5, 10, 15, 20]])

In [68]:
c = np.array([1, 2, 3, 4])
d = np.array([[2], [3], [4]])
c*d

array([[ 2,  4,  6,  8],
       [ 3,  6,  9, 12],
       [ 4,  8, 12, 16]])

In [69]:
e = np.array([1, 2, 3])
f = np.array([[2], [3], [4], [5]])
e*f

array([[ 2,  4,  6],
       [ 3,  6,  9],
       [ 4,  8, 12],
       [ 5, 10, 15]])

In [70]:
x = np.array([[1, 2, 3], [4, 5, 6]], int)
x

array([[1, 2, 3],
       [4, 5, 6]])

In [71]:
x[0][0]

1

In [73]:
x[0,2]

3

In [74]:
x = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]], int)
x[:,2:] # 전체 행의 2열 이상

array([[ 3,  4,  5],
       [ 8,  9, 10]])

In [75]:
x[1,1:3] # 1행의 1열 ~ 2열

array([7, 8])

In [77]:
x[1:3] # 1행 ~ 2행의 전체, 행렬 전체의 행의 개수가 2이기 때문에 이를 넘어가는 인덱스는 무시

array([[ 6,  7,  8,  9, 10]])

In [78]:
x = np.array(range(15), int).reshape(3, -1)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [79]:
x[:,::2]

array([[ 0,  2,  4],
       [ 5,  7,  9],
       [10, 12, 14]])

In [80]:
x[::2,::3]

array([[ 0,  3],
       [10, 13]])

In [83]:
#arange : range함수와 달리 증가값에 실수형이 입력되어도 값을 생성할 수 있음
np.arange(0, 5,0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [84]:
# 모든값이 1인 배열 만들기
np.ones(shape=(5,2), dtype=np.int8)

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]], dtype=int8)

In [85]:
# 모든값이 0인 배열 만들기
np.zeros(shape=(2,2), dtype=np.float32)

array([[0., 0.],
       [0., 0.]], dtype=float32)

In [86]:
# 공간만 확보 함. 아무 값이나 들어감
np.empty(shape=(2,4), dtype=np.float32)

array([[0.e+00, 1.e-45, 3.e-45, 4.e-45],
       [6.e-45, 7.e-45, 8.e-45, 1.e-44]], dtype=float32)